query ReadOrder ($where: OrderWhereUniqueInput!) {
  order(where: $where) {
    uid
    name
    stage
    createdAt
    updatedAt
    items {
      uid
      code
      quantity
      description
      provider
      pricing {
        uid
        amount
        currency
        type
      }
    }
    issuedTo {
      uid
      name1
      lastName1
    }
  }
}
